# Generated by Django 2.2.4 on 2019-09-14 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(blank=True, max_length=100)),
                ('reg_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('roll_no', models.IntegerField(blank=True, default=0)),
                ('course', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
