# Generated by Django 2.2.4 on 2019-09-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deptadmin', '0001_initial'),
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintPost',
            fields=[
                ('complaintId', models.AutoField(primary_key=True, serialize=False)),
                ('complainthead', models.CharField(blank=True, max_length=100)),
                ('complaintType', models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent'), ('Lost', 'Lost')], default='Normal', max_length=20)),
                ('complaintDes', models.TextField(blank=True)),
                ('departmentChoice', models.CharField(choices=[('ADMIN', 'ADMIN'), ('Chief Warden', 'Chief Warden'), ('CSE', 'CSE'), ('HOSTEL OFFICE', 'HOSTEL OFFICE')], default='ADMIN', max_length=30)),
                ('status', models.CharField(choices=[('COMPLAINT REGISTERED', 'COMPLAINT REGISTERED'), ('UNDER DEPARTMENT VIEW', 'UNDER DEPARTMENT VIEW'), ('PERSON ASSINGED TO SOLVE COMPLAINT', 'PERSON ASSINGED TO SOLVE COMPLAINT'), ('NEED SOME REMARK', 'NEED SOME REMARK'), ('SOLVED', 'SOLVED'), ('REJECTED', 'REJECTED')], default='COMPLAINT REGISTERED', max_length=50)),
                ('sRemark', models.TextField(blank=True)),
                ('assigneeRemark', models.TextField(blank=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('document', models.FileField(upload_to='doc_upload/')),
                ('departmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deptadmin.DepartmentPerson')),
                ('s_reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complain.Student')),
            ],
        ),
    ]
